### ISSUE TITLE
Separate addon for target cast bar

### ISSUE THREAD

**Issue by VidgetGaming** [wardz/ClassicCastbars#1]
Would it be possible to get a separate addon with a cast bar for your target that you can move around and resize?

**Comment by wardz** [comment]
Latest version has slash command options for setting position and disabling nameplate castbars if you dont want those. (see configuration in readme.md file)

There's currently no options for setting castbar size but it's on my to-do list. (Prob gonna be in next version) I'm also gonna add a graphical interface for the options later but that might take some time

**Comment by VidgetGaming** [comment]
I mean if you're fighting something really tall like a boss it would be nice to be able to move the castbar from the nameplate to somewhere else on the screen.

**Comment by wardz** [comment]
Sorry, that's out of the scope for this addon. You should enable [nameplate clamping](https://www.reddit.com/r/wow/comments/7kn384/clamping_nameplates_to_screen/) or use something like DeadlyBossMods for this.

**Comment by VidgetGaming** [comment]
> > to be able to move the castbar from the nameplate to somewhere else on the screen.
> 
> Sorry, that's out of the scope for this addon. You should enable [nameplate clamping](https://www.reddit.com/r/wow/comments/7kn384/clamping_nameplates_to_screen/) or use something like DeadlyBossMods for this.
> 
> If Classic has boss frames like on retail I can add castbars to those though.

I actually figured it out. I changed line 19 in AnchorManager.lua to "UIParent" which enabled me to move the target castbar around wherever I wanted on the screen.

**Comment by wardz** [comment]
That will still only show the castbar when you have a target no? If all you want do to is to move the frames you can do that through the options panel. Make sure you're using the latest version of the addon.

![Imgur](https://imgur.com/EFBJ5aV)

**Comment by VidgetGaming** [comment]
Yeah maybe I was using an old version. It didn't work with my unit frames so I never saw the cast bars.

**Comment by wardz** [comment]
I see, sounds like a bug. Which unitframes were you using?

**Comment by VidgetGaming** [comment]
LunaUnitFrames

**Comment by wardz** [comment]
LunaUnitFrames support should now be fixed in v1.0.0-next.3.

**Comment by VidgetGaming** [comment]
Awesome, I'll try it out!

**Comment by VidgetGaming** [comment]
Worked great. I could move the castbar around and place it wherever I wanted to on the screen. Top notch!
