### ISSUE TITLE
Combo addon issue

### ISSUE THREAD

**Issue by Restomagus** [wardz/ClassicCastbars#11]
ClassicCastBars is working so very well on its own!!!! I love it!

However, it does not appear to work with Dominos addon for UI manipulation.

I already reported this to the Dominos developer. I am hoping the two of you can get together to get these working together :)

**Comment by Restomagus** [comment]
If I disable Dominos Cast it works fine!

**Comment by wardz** [comment]
Seems to work fine when I tested it. What do you mean by not working, it won't show up at all?

Try updating both addons and resetting the settings.

**Comment by wardz** [comment]
Closing this, assuming it was the batching that caused the issue. If not feel free to reopen.
