### ISSUE TITLE
ClassicCastbars API

### ISSUE THREAD

**Issue by illion20** [wardz/ClassicCastbars#14]
**Is your feature request related to a problem?**
Yes

**Describe the solution or feature you'd like:**
I would like to have a function in ClassicCastbars that sends back the cast object as such:

`function addon:UnitCastingInfo(unitID)`
`	if not activeTimers[UnitGUID(unitID)] then return end`
`	return activeTimers[UnitGUID(unitID)]`
`end`

I tried to add ClassicCastbars as dependency and add the function to the main lua in your addon just to test, then call from my addon:

`local cast = ClassicCastbars.UnitCastingInfo("target")`

But its always nil

**Any additional context:**
I am a complete WoW addon noob just trying to get by in the world

**Comment by joev** [comment]
Check out LibClassicCast (maintained by me based on this codebase) or LibClassicCasterino (separate but very similar implementation by the author of Nugrunning)

**Comment by wardz** [comment]
This ^

I won't add an API for ClassicCastbars at this point.
