### ISSUE TITLE
Changing some player cast bar settings bugs out the castbar until reload

### ISSUE THREAD

**Issue by audiosmith** [wardz/ClassicCastbars#17]
Hi

I know it's a pretty new feature and has some things to be ironed out.
I'm enjoying having cast times on my cast bar.
Just that configuring the cast bar often bugs it out until you reload, tasks such as changing the size.

Thanks

**Comment by wardz** [comment]
Oh darn, thought I fixed that. Will look into it again, ty.

**Comment by wardz** [comment]
Does this still happen in v1.1.0? I'm having a hard time to replicate this myself.

**Comment by audiosmith** [comment]
Seems fixed now thanks!
