### ISSUE TITLE
Can't move player castbar if disable "auto position"

### ISSUE THREAD

**Issue by foobarna** [wardz/ClassicCastbars#18]
**What is the problem? Is there any Lua errors?**
None

**What steps will reproduce the problem?**
Enable player castbar, toggle test, disable "auto position"

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
Yes.

**Was it working in a previous version? If yes, which was the last good one?**
Feature nonexistent.

**Any additional info? If you play on a non english client, please include your locale:**
europe

**Comment by wardz** [comment]
Hmm weird, works fine here. Does a reload ui fix it or does the moving never work at all?

**Comment by foobarna** [comment]
Yes, a /rl did the trick.

It doesn't bug out like before. Thanks! :)
