### ISSUE TITLE
No castbars for the Hunter's "Aimed Shot" abilities.

### ISSUE THREAD

**Issue by Feedbk** [wardz/ClassicCastbars#19]
ClassicCastbars v1.0.9

The addon does not create a castbar for the Hunter's "Aimed Shot" ability (Rank 1 - 4). I cannot verify if this issue also affects the higher ranks (Rank 5 - 6). 

I am unsure if this has been an issue in previous versions of the addon. "Aimed Shot" seems to be the only ability that is affected, as the addon is working without any issue for other items and abilities (Mount, Hearthstone, Profession crafting etc.)

**Comment by wardz** [comment]
This addon doesn't actually create a new castbar for the player, it just skins the Blizzard castbar built into the game already. I'll look into if it's possible to modify it to show Aimed Shot soon but no promises.
