### ISSUE TITLE
Elvui

### ISSUE THREAD

**Issue by wiggills** [wardz/ClassicCastbars#20]
Is their anyway to connect this to elvui? and move it where you want?

**Comment by wardz** [comment]
It should work with ElvUI already. Does it not show up on the target frame?

**Comment by wiggills** [comment]
I was struggling with moving it around my UI. I turned it off and back on. It worked. I appreciate the follow up.

**Comment by wardz** [comment]
Cool. Just curious, was this for the player castbar or target/nameplate?

**Comment by wiggills** [comment]
Player castbar

**Comment by wiggills** [comment]
Target and player. Was so frustrating haha

**Comment by wardz** [comment]
I added a few tweaks to previous version that should hopefully fix this. Feel free to reopen ticket if the issue still occurs.
