### ISSUE TITLE
Sacrifice does not display

### ISSUE THREAD

**Issue by Dragzzzter** [wardz/ClassicCastbars#26]
When fighting Zevrim Thornhuf it shows the Intense Pain cast correctly. But when he starts to cast sacrifice it doesn't show up on CCB. This is very frustrating when farming dm east solo.

Otherwise great addon :)
Greetings

**Comment by wardz** [comment]
Weird, I've been farming him a lot and it always has shown up for me. Are you using the English game client or a different locale? Also make sure you're using the latest version of the addon.

**Comment by Dragzzzter** [comment]
I'm using the German Client - I already updated my add-on but it doesn't work. The German Client could be the Problem. I'll test that on the next occasion.

**Comment by wardz** [comment]
It's most likely because of the German client then. I will look into it soon.

**Comment by wardz** [comment]
Try and see if v1.1.6 fixes it

**Comment by Dragzzzter** [comment]
I just tried it, but it still doesn't show up. The same behaviour as of 1.1.5

**Comment by wardz** [comment]
Fixed it now. Seems like the German client has two different names for Sacrifice, "Opferung" and "Opfern", both are now included. I will release an update tomorrow or friday. (If you don't want to wait you can download from Github master and replace the Data.lua file with your existing Data.lua file)
