### ISSUE TITLE
Target castbar texture - out of border

### ISSUE THREAD

**Issue by foobarna** [wardz/ClassicCastbars#27]
**What is the problem? Is there any Lua errors?**
As seen below, the castbar texture is getting out of its border.

![castbar_texture](https://user-images.githubusercontent.com/477645/69877049-d0430100-12c9-11ea-9456-b0c66c76f21d.png)

**What steps will reproduce the problem?**
Using the default castbar texture and default border - no custom textures in Interface folder.

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
Yes.

**Was it working in a previous version? If yes, which was the last good one?**
It's like this since I've used the addon first time (~2 months ago).

**Any additional info? If you play on a non english client, please include your locale:**
No extra stuff.

**Comment by wardz** [comment]
Give it a try in v1.1.7, should be fixed although the top left corner might have 1px of texture still missing. (hard to fix without causing side effects).

If v1.1.7 still doesn't fix it please include your monitor resolution and aspect ratio.
