### ISSUE TITLE
Bad border on player castbar

### ISSUE THREAD

**Issue by sigzegv** [wardz/ClassicCastbars#28]
**What is the problem? Is there any Lua errors?**
The border castbar for player displays with incorrect inset (and seems to be too thick)
![image](https://user-images.githubusercontent.com/6304596/70421630-73cea700-1a6a-11ea-9072-f702a0c7deba.png)
In this example player's castbar as same size as target's one
(I may not be caused by custom UF because it's just a reskin on blizzard's one)
**What steps will reproduce the problem?**
Just configure player castbar

**Comment by wardz** [comment]
Seems like setting the castbar height too low screws it up. Will look into it.

**Comment by sigzegv** [comment]
no issues with this height on target's cast :)

**Comment by wardz** [comment]
Does a /reload fix it for you or is it always like that no matter what?

**Comment by sigzegv** [comment]
I think I upgrade to your last commit (1.1.8?) before seeing this message. I don't have the issue anymore, maybe because of that or maybe because of a reload, but seems cool now.

**Comment by wardz** [comment]
The comment referenced above is not live yet, but I think it should fix the issue completely. I will upload the fix on wednesday together with the new WoW patch.
