### ISSUE TITLE
Preventing me to click enter battleground

### ISSUE THREAD

**Issue by Nillx** [wardz/ClassicCastbars#29]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'ClassicCastbars' tried to call the protected function 'AcceptBattlefieldPort()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `AcceptBattlefieldPort'
FrameXML\StaticPopup.lua:689: in function `OnAccept'
FrameXML\StaticPopup.lua:5003: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by wardz** [comment]
Should be fixed now in newest update.

**Comment by Nillx** [comment]
thanks
