### ISSUE TITLE
Implement and contribute to LibClassicCasterino

### ISSUE THREAD

**Issue by saenic** [wardz/ClassicCastbars#30]
There is a library which detects spell casts by units called LibClassicCasterino. It is implemented by e.g. Details Damage Meter, Quartz casting bar, etc. Currently ClassicCastbars has its own database of spell casts, interrupts, delays, etc.

In order for all these addons to have the same information, it would be good, if ClassicCastbars would also implement this library and even more important provide the additional information about interrupts and delays to the library.

**Comment by wardz** [comment]
Sorry, its too much work to implement at this point in time. This addon is now mostly in maintenance mode.
