### ISSUE TITLE
Certain actions cause Lua errors.

### ISSUE THREAD

**Issue by silverhawke249** [wardz/ClassicCastbars#31]
**What is the problem? Is there any Lua errors?**
Performing certain actions cause the following Lua error to pop out repeatedly, as long as action is being performed: `Interface\AddOns\ClassicCastbars\core/Frames.lua:279: attempt to index a nil value`

**What steps will reproduce the problem?**
Activating the torch switch in Jandice Barov's room.
Looting the Skin of Shadow in Ilucia Barov's room.

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
Haven't tried yet due to position of known trigger, will try when a more accessible reproduction step is found.

**Any additional info? If you play on a non English client, please include your locale:**
Nil.

**Comment by wardz** [comment]
Does this still happen in v1.2.9 aswell?

**Comment by silverhawke249** [comment]
I'm pretty sure I'm on v1.2.9. I don't use any big UI modifying add-ons; for the castbar frame, I only have this addon installed. But if I find out another action that can cause the same error that's not in Scholomance, I'll let you know.

**Comment by wardz** [comment]
Think it should be fixed now, will upload the fix to Curseforge/WoWInterface in a day or two

**Comment by silverhawke249** [comment]
I just reproduced the errors with just this addon active.
Good to hear that it should be fixed, but I'll post the dump anyway :P https://pastebin.com/RJMiWJnS

**Comment by wardz** [comment]
Can you confirm if v1.2.10 fixes it?

**Comment by silverhawke249** [comment]
Confirmed, it doesn't cause Lua errors anymore. Thanks!
