### ISSUE TITLE
Castbars Not Functioning

### ISSUE THREAD

**Issue by Bsting54** [wardz/ClassicCastbars#34]
**What is the problem? Is there any Lua errors?**
When a mob starts to cast something, i get an error and the addon no longer functions.  See copied error

Date: 2020-04-02 09:38:21
ID: 1
Error occured in: Global
Count: 2
Message: ..\AddOns\ClassicCastbars\ClassicCastbars.lua line 99:
   attempt to call field 'UnitAuraWithBuffs' (a nil value)
Debug:
   ClassicCastbars\ClassicCastbars.lua:99: CheckCastModifier()
   ClassicCastbars\ClassicCastbars.lua:136: StartCast()
   ClassicCastbars\ClassicCastbars.lua:156: StartAllCasts()
   ClassicCastbars\ClassicCastbars.lua:209:
      ClassicCastbars\ClassicCastbars.lua:170
   (tail call): ?
   (tail call): ?
Locals:
self = <unnamed> {
 NAME_PLATE_UNIT_REMOVED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:441
 StoreCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:170
 CreateOrUpdateSecureFocusButton = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:425
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:323
 SkinPlayerCastbar = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:338
 ToggleUnitEvents = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:291
 CheckCastModifier = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:68
 DeleteCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:213
 NAME_PLATE_UNIT_ADDED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:430
 DisplayCastbar = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:239
 SetBorderShieldStyle = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:76
 AnchorManager = <table> {
 }
 SetFocusDisplay = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:474
 StartCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:128
 SetCastbarFonts = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:194
 CreateFadeAnimationGroup = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:212
 SetCastbarIconAndText = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:56
 activeFrames = <table> {
 }
 CastPushback = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:230
 StopCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:140
 GROUP_ROSTER_UPDATE = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:452
 GetCastbarFrame = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:29
 SetTargetCastbarPosition = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:42
 PLAYER_TARGET_CHANGED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:423
 db = <table> {
 }
 PLAYER_GUID = "Player-4372-00618E47"
 ClearFocus = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:457
 activeTimers = <table> {
 }
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:338
 SetCastbarStatusColorsOnDisplay = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:226
 GROUP_JOINED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:452
 0 = <userdata>
 UNIT_AURA = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:408
 SetLSMBorders = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:169
 defaultConfig = <table> {
 }
 StartAllCasts = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:151
 SetCastbarStyle = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:110
 HideCastbar = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:275
 StopAllCasts = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:161
 GetUnitType = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:57
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:486
}
unitID = "target"
cast = <table> {
 isPlayer = false
 maxValue = 2.500000
 timeStart = 1728735.783000
 unitGUID = "Creature-0-4380-0-3-1834-000005E760"
 spellID = 25292
 endTime = 1728738.283000
 icon = 135920
 spellName = "Holy Light"
}
libCD = <table> {
 Register = <function> defined @Interface\AddOns\ZPerl\Libs\LibClassicDurations\core.lua:690
 dataVersions = <table> {
 }
 guidAccessTimes = <table> {
 }
 GetAuraDurationByUnit = <function> defined @Interface\AddOns\ZPerl\Libs\LibClassicDurations\core.lua:665
 Talent = <function> defined @Interface\AddOns\ZPerl\Libs\LibClassicDurations\core.lua:159
 enableEnemyBuffTrack
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.00.11303.00
  AtlasClassicWoW, vv1.47.00.11303.00
  AtlasLootClassic, vv1.4.7
  AtlasLootClassicData, vv1.4.7
  AtlasLootClassicDungeonsAndRaids, vv1.4.7
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.9.0
  ClassicCastbars, vv1.3.2
  ClassicCastbarsOptions, v
  Coordinates, v2.1.0
  DBMCore, v1.13.42
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExoLink, v1.0.1
  ExoLinkBIS, v1.0.1
  ExtendedCharacterStats, v2.2.1
  GatherMate2, v1.45.5
  GroupCalendar, v
  HideRaidManager, v1.0
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixPlus, v1.13.56
  NugEnergy, v1.13.14
  OmniCC, v8.3.5
  Pawn, v2.3.24
  Questie, v5.10.0 0 fd3ff918
  Recount, vv1.13.4a
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.12
  TomCats, v0.0.2
  WeaponSwingTimer, v4.1.0
  ZPerl, v5.9.3
  ZPerlArcaneBar, v
  ZPerlParty, v
  ZPerlPartyPet, v
  ZPerlPlayer, v
  ZPerlPlayerBuffs, v
  ZPerlPlayerPet, v
  ZPerlRaidAdmin, v
  ZPerlRaidFrames, v
  ZPerlRaidHelper, v
  ZPerlRaidPets, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=656)

**What steps will reproduce the problem?**

**Does the issue still occur when all addons except ClassicCastbars are disabled?**

**Any additional info? If you play on a non English client, please include your locale:**

**Comment by wardz** [comment]
Fixed now. Seems like one of your addons is embedding a very old and outdated version of LibClassicDurations which screws it up.

Will upload the fix tomorrow.

**Comment by Bsting54** [comment]
Great, thank you so much.  I really appreciate it...your addon is essential for me :)
