### ISSUE TITLE
does not work with zperl unite frames 

### ISSUE THREAD

**Issue by faberz** [wardz/ClassicCastbars#36]
**What is the problem? Is there any Lua errors?**
does not work with zperl unite frames anymore but only on other players works for mobs fine starts working only when i disable whole zperl addon with all options was working fine yesterday any ideas what should i do? got this erro anytime other player casts spell 
Message: Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:99: attempt to call field 'UnitAuraWithBuffs' (a nil value)
Time: Fri Apr  3 13:44:21 2020
Count: 2
Stack: Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:99: attempt to call field 'UnitAuraWithBuffs' (a nil value)
Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:99: in function `CheckCastModifier'
Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:136: in function `StartCast'
Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:156: in function `StartAllCasts'
Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:209: in function <Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:170>
(tail call): ?
(tail call): ?

Locals: self = <unnamed> {
 NAME_PLATE_UNIT_REMOVED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:441
 StoreCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:170
 CreateOrUpdateSecureFocusButton = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:425
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:323
 SkinPlayerCastbar = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:338
 ToggleUnitEvents = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:291
 CheckCastModifier = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:68
 DeleteCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:213
 NAME_PLATE_UNIT_ADDED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:430
 DisplayCastbar = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:239
 SetBorderShieldStyle = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:76
 AnchorManager = <table> {
 }
 SetFocusDisplay = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:474
 StartCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:128
 SetCastbarFonts = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:194
 CreateFadeAnimationGroup = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:212
 SetCastbarIconAndText = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:56
 activeFrames = <table> {
 }
 CastPushback = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:230
 StopCast = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:140
 GROUP_ROSTER_UPDATE = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:452
 GetCastbarFrame = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:29
 SetTargetCastbarPosition = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:42
 PLAYER_TARGET_CHANGED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:423
 db = <table> {
 }
 PLAYER_GUID = "Player-4465-0085515F"
 ClearFocus = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:457
 activeTimers = <table> {
 }
 ZONE_CHANGED_NEW_AREA = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:338
 SetCastbarStatusColorsOnDisplay = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:226
 GROUP_JOINED = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:452
 0 = <userdata>
 UNIT_AURA = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:408
 SetLSMBorders = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:169
 defaultConfig = <table> {
 }
 StartAllCasts = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:151
 SetCastbarStyle = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:110
 HideCastbar = <function> defined @Interface\AddOns\ClassicCastbars\core/Frames.lua:275
 StopAllCasts = <function> defined @Interface\AddOns\ClassicCastbars\ClassicCastbars.lua:161
 GetUnitType = <function> d

**What steps will reproduce the problem?**
did reinstal both addons 

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
no

**Any additional info? If you play on a non English client, please include your locale:**

**Comment by wardz** [comment]
Related to issue #34 - i've uploaded the fix now.

**Comment by faberz** [comment]
> Related to issue #34 - i've uploaded the fix now.

i just need to update addon ore?

**Comment by wardz** [comment]
Yes
