### ISSUE TITLE
Party castbars showing up in raid

### ISSUE THREAD

**Issue by FrittenKeeZ** [wardz/ClassicCastbars#38]
Sometimes the party castbars will show in raid, in the position they would normally be at in a party, but it's not at all consistent.

I'm using Blizzard Raid Frames, and can't see to find a pattern for when it happens.

**Comment by wardz** [comment]
u mean they attach to the raid frames? That's intended.

**Comment by FrittenKeeZ** [comment]
I'll try to take a screen shot next time it happens... it's kinda hard to explain :)
They overlap the raid frames, making it difficult to see player health and such.

**Comment by wardz** [comment]
As of v1.3.6 party castbars will now be disabled when in groups larger than 5. Guessing this should fix it.
