### ISSUE TITLE
Pushback

### ISSUE THREAD

**Issue by Aviana** [wardz/ClassicCastbars#4]
**What is the problem? Is there any Lua errors?**
The pushback mechanic uses wrong values.

**What steps will reproduce the problem?**
Tested with player casting event "UNIT_SPELLCAST_DELAYED". 

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
yes

**Was it working in a previous version? If yes, which was the last good one?**
no

**Any additional info? If you play on a non english client, please include your locale:**
https://wow.gamepedia.com/index.php?title=Interrupt&oldid=305918

**Comment by wardz** [comment]
Thanks, I'll look into it later. (currently on vacation so gonna have to wait 2-3 weeks)
