### ISSUE TITLE
InFlight Timers

### ISSUE THREAD

**Issue by orionshock** [wardz/ClassicCastbars#40]
**Is your feature request related to a problem?**
No

**Describe the solution or feature you'd like:**
Would like to show InFlight Timers for when party members on on a taxi as their Cast Bar.

**Any additional context:**

I've made a request to the addon Author for InFlight (https://www.wowinterface.com/downloads/info11178-InFlight.html#info), seems like comments section is the only way to get a hold of them.

Tho Im sure other addons are out there that do the same.

**Comment by wardz** [comment]
Sorry, that is completely out of scope for this addon.
