### ISSUE TITLE
Extract cast tracking to library

### ISSUE THREAD

**Issue by chrisd08** [wardz/ClassicCastbars#42]
This is probably a fairly substantial task but it would be super useful to have your casting data usable as a library, similar to LibThreatClassic2, or LibClassicCasterino (which unfortunately is not receiving many updates). Something akin to [this ](https://github.com/rgd87/LibClassicCasterino/blob/master/LibClassicCasterino.lua#L326)would mean other addons could utilise the same data and not have to re-invent the wheel and increase addon bloat.

**Comment by wardz** [comment]
Not for now but I'll reconsider this after the summer when I have more time. It's a lot of work to rewrite this into a library at this point and the addon is already basically in maintenance mode.

(Sorry for late reply, thought I already had replied)
