### ISSUE TITLE
Spell Text Anchor point

### ISSUE THREAD

**Issue by Eurymachus** [wardz/ClassicCastbars#43]
Is your feature request related to a problem? No

Describe the solution or feature you'd like:
The anchor point (alignment) of text at the moment is centered, so when moving text to the left or right within a casting bar text grows outside the bar.

If we allow the anchor point of spell text to be set left, right or center the text can grow from those points. This will enable the placement of text to the left, right or center of a cast bar preventing text from growing outside the bar when placed relative.

Any additional context: N/A

**Comment by wardz** [comment]
Sure, will add in next release.

**Comment by wardz** [comment]
Added now.

**Comment by Eurymachus** [comment]
Hey Wardz! Thanks for your work so far. Just did some testing and the text anchor/align doesn't seem to work as intended.
Setting the alignment to the 'LEFT' the text should grow from the left, but as you can see the text still changes position and is not aligned correctly.
![image](https://user-images.githubusercontent.com/1562316/86993469-fd2e8f00-c19b-11ea-911f-98e9801b7856.png)
![image](https://user-images.githubusercontent.com/1562316/86993423-e25c1a80-c19b-11ea-96d1-436d01a89365.png)

**Comment by Eurymachus** [comment]
So below is the 'CENTERED' option;
![image](https://user-images.githubusercontent.com/1562316/86993736-ae352980-c19c-11ea-9cf3-25057ba0b7cc.png)
Below is the 'LEFT' option;
![image](https://user-images.githubusercontent.com/1562316/86993756-c0af6300-c19c-11ea-83ed-79f0ebb9d3e0.png)
This is when 'X' = 0.
What should happen when setting the anchor point is that the text 'grows' from the 0 point of 'X' so it should look more like this;
![image](https://user-images.githubusercontent.com/1562316/86994068-6b278600-c19d-11ea-9330-28da21d9d172.png)
Then no matter the length of the text it would always grow from the 'X' point.
Sorry for the crudeness of the image.

**Comment by wardz** [comment]
Ah I see. Will take another look at it when I get home from vacation (2~ weeks)

**Comment by wardz** [comment]
Try v1.3.10
