### ISSUE TITLE
[Lua error]

### ISSUE THREAD

**Issue by Altoholic** [wardz/ClassicCastbars#44]
**What is the problem? Is there any Lua errors?**
1x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:840: Method settMiddleHideCombat doesn't exist in handler for type func
[C]: ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:840: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[C]: ?
...assicCastbars_Options\Libs\AceGUI-3.0\AceGUI-3.0-41.lua:72: in function <...assicCastbars_Options\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
...assicCastbars_Options\Libs\AceGUI-3.0\AceGUI-3.0-41.lua:306: in function `Fire'
...nc\libs\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua:68: in function <...nc\libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

**Any additional info? If you play on a non English client, please include your locale:**

It occurred while configuring NovaWorldBuff (more specifically : while checking "buff drop warning").

I was not able to reproduce it.

**Comment by wardz** [comment]
This is an error with NovaWorldBuff. ClassicCastbars just happens to be the first addon that loads and instantiates the Ace3 libraries.
