### ISSUE TITLE
Castbar does not show on NAXX LAST BOSS (Kel'Thuzad)

### ISSUE THREAD

**Issue by a339791012** [wardz/ClassicCastbars#46]
**What is the problem? Is there any Lua errors?**

Castbar is working most of the time, it is working on everything (healer cast / mage cast), but it just does not work on 
Kel'Thuzad boss. 

**What steps will reproduce the problem?**
idk

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
i tried to reinstall it, but it does not work.

**Any additional info? If you play on a non-english client, please include your locale type:**
yes, I'm playing other language wow classic (Chinese) for a year+. I never have a problem with it.

**Comment by wardz** [comment]
Hmm, seems to be an issue with the chinese client's language. Does both of these translate to Frostbolt? " 寒冰箭 ", " 冰霜箭 ". I will try adding both of them to next version, hopefully that fixes it.

**Comment by a339791012** [comment]
Dear  Thomas,

Thank you! i would really appreciate it. I could not wait the next update.
Hopefully it helps to see the cast on Frostbolt, right now i could not
interrupt the cast on NAXX - Kel'Thuzad.

thank you very much again!

Stay Safe!

Siu

**Comment by a339791012** [comment]
the problem has been solved, i can see Kel'Thuzad frostbolt cast now!. thank you! again! :)
