### ISSUE TITLE
Player Castbar issue

### ISSUE THREAD

**Issue by Truckrental** [wardz/ClassicCastbars#48]
**What is the problem? Is there any Lua errors?**
Every time I bring out my pet or put my pet away, for my hunter. my cast bar gets reset to the default position. Same thing happens on my priest when I mind control someone. So I'm guessing the pet nameplate is what's causing the reset

No Lua errors

![123](https://user-images.githubusercontent.com/82984167/115636586-dfb65600-a2d3-11eb-9f5e-6165b71647df.png)
![456](https://user-images.githubusercontent.com/82984167/115636597-e349dd00-a2d3-11eb-87de-8c15663b43d6.png)

**What steps will reproduce the problem?**
Put pet away
move plater castbar
pull pet out
player castbar will be in default location 

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
yes

**Any additional info? If you play on a non-english client, please include your locale type:**

**Comment by wardz** [comment]
Should be fixed now in v1.3.23.
