### ISSUE TITLE
after the update timer for some skills are incorrect

### ISSUE THREAD

**Issue by junchao-1837136** [wardz/ClassicCastbars#49]
one example is warlock's summon imp. timer is 8sec when in reality its 10

**Comment by wardz** [comment]
Which update, classic patch 1.13.7 or latest addon update?

Casts with talent reductions such as warlock summons are not accurate since you can't detect other people's talent. With 2/2 Master Summoner its a 6sec cast time.

**Comment by junchao-1837136** [comment]
I just remembered it always being accurate before patch 1.13.7. Same for some other spells with wrong cast time that I can't remember on top of my head but used to always be correct. Is casts with talent speed reduction not accurate always a thing or is it something new after 1.13.7?

**Comment by wardz** [comment]
It's been like that for all of Classic. If you target yourself it should show correct cast time, but not if you target other players.
