### ISSUE TITLE
No castbars shown at all - even on default settings.

### ISSUE THREAD

**Issue by ujellyx** [wardz/ClassicCastbars#5]
**What is the problem? Is there any Lua errors?**
No.

**What steps will reproduce the problem?**
Basically have someone else cast something - enemy or friend.

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
Yes.

**Was it working in a previous version? If yes, which was the last good one?**
No.

**Any additional info? If you play on a non english client, please include your locale:**
I was testing it during the stresstest and even on default settings it didn't show any castbars - neither on the nameplates, nor below the target-frame.

Screenshot:
https://i.imgur.com/6CpkaAS.jpg

**Comment by wardz** [comment]
Blizzard broke it in their latest build, all spellIDs are removed from the combat log. I'll try to add a workaround for it soon.

**Comment by wardz** [comment]
Should be fixed now in version 1.0.0-next.5. (Make sure to download from Curseforge or WoWInterface, not Github)

Note that Blizzard removed the ability to distinguish between spell ranks in the combat log, so now cast times are always based on the highest rank.
