### ISSUE TITLE
Auto position adjustmend

### ISSUE THREAD

**Issue by mav676** [wardz/ClassicCastbars#51]
Didnt work as intended , bugged and cover some buff/debuffs on frames 
![WoWScrnShot_052421_003635](https://user-images.githubusercontent.com/84689630/119281678-3bf7f700-bc3f-11eb-8dee-b05fe9816c9d.jpg)

**Comment by wardz** [comment]
Atm it only supports auto positioning when using default debuff sizes. Will try and add support for custom sizes next version. Meanwhile I recommend using manual positioning.
