### ISSUE TITLE
Uninterruptible Not Showing

### ISSUE THREAD

**Issue by jbaymen27** [wardz/ClassicCastbars#53]
**What is the problem? Is there any Lua errors?**  I know you say that the addon will learn for the future, but it is not.  You also show what Uninterruptible will look like (the original animation) and that does not happen.

**What steps will reproduce the problem?** 

**Does the issue still occur when all addons except ClassicCastbars are disabled?** Yes

**Is this for Classic or TBC client?** TBC

**Any additional info? If you play on a non-english client, please include your locale type:**

**Comment by wardz** [comment]
I haven't added the feature yet for TBC sorry, haven't had any time. Atm it only works for Classic era. Not sure when I'll get the time to add it.

**Comment by jbaymen27** [comment]
All good. Just making sure I wasn’t crazy. Thanks for the add on. Appreciate it.
