### ISSUE TITLE
weak auras with castbars break this

### ISSUE THREAD

**Issue by chorp-cpu** [wardz/ClassicCastbars#58]
tbc 1.4.2
it seems like every weak aura that has a castbar, like class huds break this (a full empty selfcast bar from classiccastbars with a spell will be stuck in the center of the screen never changing).
for example: luxthos warlock hud: https://wago.io/51yjJjm7_/3

can something be done about this? so far i either have to disable ccb or delete the self cast bar section of the wa.

also why did you delete all curse addon discussion/comments?

**Comment by wardz** [comment]
(Sorry for late reply, didn't get any email notifications so I didn't notice your ticket before now.)

I'm assuming you're talking about the default player castbar for your own character? This addon doesn't actually create a new castbar for the player, it just skins the default Blizzard one. If you have several addons modifying this same castbar frame there will be conflicts, so you have to decide which one you want enabled. You can disable ClassicCastbars from skinning the player castbar in the addon's options by disabling the player module. (Default off)

**Comment by chorp-cpu** [comment]
which site do you use for discussions?

**Comment by wardz** [comment]
Github issue tickets. You can send in questions here aswell by using the blank template.

This addon is now mostly in maintenance mode so more forms of discussions are not really needed. For private inquiries you can PM on Curseforge still.
