### ISSUE TITLE
Game doesn't recognize the addon

### ISSUE THREAD

**Issue by Splinz** [wardz/ClassicCastbars#6]
Your last build is not recognized by my wow client, the file is named correctly in the addons folder ("ClassicCastBars"), my client is in english text , french dialog setup

**Comment by wardz** [comment]
Did you download from Curseforge or WoWInterface? Downloading from Github or any other site is not supported.

**Comment by Splinz** [comment]
I did download it from github now that i tried to install it from the curse forge file it works thank you
