### ISSUE TITLE
[Bug]: castbar target, but not player, fails with some macroed abilities

### ISSUE THREAD

**Issue by chorp-cpu** [wardz/ClassicCastbars#61]
### What happened?

to easily demonstrate this use this macro while targeting yourself:
#showtooltip
/dismount
/use [mod:alt]Great Purple Elekk; Cenarion War Hippogryph
/use Great Purple Elekk

target (in this case you) castbar instantly fails and vanishes
player castbar functions normally

i first noticed it happening in battlegrounds. where target castbar claims opponent failed/stopped casting, when i can obviously see they are chain nuking me or healing.  ofcourse there i couldn't communicate with them to see what their macro was doing.

### Game Version

The Burning Crusade Classic

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by wardz** [comment]
Will look into it, but seems to only happen for the player here, and not other targets.
