### ISSUE TITLE
[Bug]: Issue with the Y-position on the nameplate

### ISSUE THREAD

**Issue by Caires11** [wardz/ClassicCastbars#62]
### What happened?

Hello, I am using this addon since the start of wow classic and I love it. The only issue that I have with this is the following ''bug'': You cannot precisely change the Position Y in the castbar nameplate menu. I can do 1, -9, and -19 for example but not -3 or -4. It is in steps of 10 only and the difference in position is quite huge. Is it possible to fix that so players can adjust the Y axis for the castbar on nameplates more precisely? So that they can adjust them on the difference of steps of 1 instead of 10? I use this addon in combination with plater.

Hope to hear from you.

Best regards,

A fan of this addon

### Game Version

The Burning Crusade Classic

### Game Language

English

### Any additional info?

No

**Comment by wardz** [comment]
Hi. There's an editbox right below the sliders that you can click and manually type in the numbers you want, then hit enter to save. Decimals will be rounded to nearest integer.

**Comment by Caires11** [comment]
Hello, I can see them, but if you type it manually and then confirm that, then it won't work and when you open back the settings its -9 or -19 again. You can type the value you want, but it wont save it, it will just go back to the ones that you can set with the slider.

**Comment by Caires11** [comment]
I also tested it without any other addon activated and it is still the same. Manually entering a number doesn't work, and you can only slide on the sliderbar in steps of 10.

**Comment by wardz** [comment]
Hmm weird, it saves properly for me on both TBC & classic era client. Can you confirm if it's still not saving the value in v1.4.4 update?

Sadly it's not possible to change the slider behaviour as it's from a third party library and not made by me. When using large numbers it'll always use steps in 5-10 ish, even if you hard configure it to use '1' as a step value.

If you still can't get it to work, you can manually change the XY positions using these chat commands:
```
/run ClassicCastbars.db.nameplate.position[2] = 10
/run ClassicCastbars.db.nameplate.position[3] = 12
```
(Change 10 and 12 to whatever number you want. You will have to restart the castbar to see the changes)

**Comment by Caires11** [comment]
@wardz I just updated from 1.4.3 to 1.4.4. Sliders now go in steps of 5 instead of 10, and the manual adjustment works :) Great!

**Comment by Caires11** [comment]
A mistake I also may have made is not pressing enter after inserting a value and directly press ''Okay''
