### ISSUE TITLE
Can't "Toggle Player Castbar" anymore

### ISSUE THREAD

**Issue by vgullotta8** [wardz/ClassicCastbars#65]
Since the recent update, I am unable to move my castbar anymore.  When I click to toggle player castbar (or anycastbar for that matter) nothing happens. You don't get the moveable castbar anymore.

**Comment by vgullotta8** [comment]
Wow that was fast! Confirmed fixed, just tested it. Thanks!!

**Comment by wardz** [comment]
Sweet, was just a blunder so easy to fix :p
