### ISSUE TITLE
[Bug]: Gargoyle cast bar intermittently not working

### ISSUE THREAD

**Issue by Wy-503** [wardz/ClassicCastbars#68]
### What happened?

Death knight gargoyle cast bar is intermittently not working.

When it is casting its initial cast it typically shows it properly. The 2nd cast or later only shows when it completes. if the cast is stopped in someway (LoS, kick etc.) then the cast bar once again works for the initial cast but not after. IO have attached a short video to show this. 

I tested this with no addons enabled other than classic cast bars, and the issue persisted. When i disabled classic cast bar, the problem resolved and the default cast bar showed the gargoyles casts properly.

I will attach a video of the issue below.

https://user-images.githubusercontent.com/116938688/198817177-33d4a073-eb0e-40e7-ba9e-0d5e581ebcd7.mp4

### Game Version

Wrath of the Lich King

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by wardz** [comment]
fixed some time ago in commit 28837bc i think, closing. If anyone still has this issue let me know.
