### ISSUE TITLE
[Bug]: Castbar texture is getting out of the border with new 3.4.1 update on WOLTK classic

### ISSUE THREAD

**Issue by ekinsenler** [wardz/ClassicCastbars#73]
### What happened?

After the 3.4.1 updated castbar texture is getting out of its border and hides the border frame and occasionally castbar lingers after cast has been over or interrupted.

### Game Version

Wrath of the Lich King

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

None

**Comment by ekinsenler** [comment]
![WoWScrnShot_021123_185036](https://user-images.githubusercontent.com/15309509/218277431-1aec6038-210f-4ede-b792-b398db077dd1.jpg)
Texture still getting out of its border, attaching the screenshot

**Comment by wardz** [comment]
Do you have any texture packs installed i.e dark ui textures? Not able to reproduce this at the moment

**Comment by ekinsenler** [comment]
yes I am using Riiz ui texture pack but this was happening even when I remove that. This my current texture, it got partially fixed on the last update but still doesn't fit in its border.
![WoWScrnShot_021423_221128](https://user-images.githubusercontent.com/15309509/218866643-faf42999-179e-44bd-8300-e22a9ac577c3.jpg)

**Comment by RevinderDev** [comment]
Same behaviour for me but I am not using any new texture packs (other than [icon packs](https://www.wowinterface.com/downloads/info25064-CleanIcons-MechagnomeEdition.html)).

It is worth noting, that it only happens for `focus` castbar, not target one for me.
![image](https://user-images.githubusercontent.com/32570664/219395741-2a1d365f-c4b7-4769-8a24-58573271b24b.png)

**Comment by wardz** [comment]
@ekinsenler Try latest update, also added new options under castbar size panel that allows changing border texture width/height so custom textures should work. This specific texture doesn't stretch automatically so it instead has to be calculated manually :/

@RevinderDev Weird, can you confirm you're using v1.5.4 or greater?

**Comment by RevinderDev** [comment]
I was on v1.5.2

I can confirm the issue is gone on v1.5.5 since this one is the newest.
Thank you! <3
