### ISSUE TITLE
[Bug]: Does not show cast bars

### ISSUE THREAD

**Issue by Ememysuss** [wardz/ClassicCastbars#74]
### What happened?

I installed the addon. Had issues displaying the cast bars. 
Steps i did in following order.

-Tried different settings, No change.
- Reloaded the client. No change
- Disabled all addons. No change
- Removed the Cache, WTF and Addon folder. No change
- Downloaded two older versions of classiccastbards. No change.
- Used the recommended /script command. TWICE! No change.
" /run ClassicCastbarsDB=nil;ClassicCastbarsCharDB=nil;EnableAddOn("ClassicCastbars");EnableAddOn("ClassicCastbars_Options")ReloadUI();"
 
- Resetet couple times the settings of my client to default, double checked all options. No change.

Im playing an Rogue, tried in pvp against my friend, and Pve enemys. Sap, gouge nothing will be displayed. 
In settings "Toggle Testing Target" works.
But thats it.

EDIT:

**I realized only selfcasting spells, like my mount or applying poisons to my sowords do show up.** 

### Is there any errors?

```shell
No errors show up
```

### Game Version

Classic Era

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by wardz** [comment]
What do you mean by Sap + Gouge? Those don't have casting times
