### ISSUE TITLE
[Bug]: player castbar is overlapping the border for some reason

### ISSUE THREAD

**Issue by sveukurac** [wardz/ClassicCastbars#75]
### What happened?

![castbar1](https://user-images.githubusercontent.com/125900666/220148031-d27defa4-e3d5-43f1-9498-92ddb1657504.png)
This issue started happening out of no where.
So basically I'm using original blizzard textbar and border texture is on default.
Sometimes it works and sometimes I just have to /reload multiple times for it to start working normally or I have to swap between castbar texture.

### Game Version

Wrath of the Lich King

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

### Any additional info?

![castbar1](https://user-images.githubusercontent.com/125900666/220151427-4e3ae920-666f-4dae-9a36-d8377d29c6f5.png)

**Comment by sveukurac** [comment]
I don't know why is this happening,it only affect my bar "player", it's really getting annoying that I have to switch to different style from time to time or reload multiple times to get it to work properly. Addon is on latest update.

**Comment by wardz** [comment]
Should be fixed now in v1.5.6
