### ISSUE TITLE
Buffs overlapping ClassicCastbars

### ISSUE THREAD

**Issue by Akrololz** [wardz/ClassicCastbars#76]
Hello! Buffs on frames are overlapping castbars if "Auto Position Castbar" is disabled, frame level doesn't do anything, any way of making ClassicCastbars be over the buffs? 
![image](https://user-images.githubusercontent.com/41456278/226691297-946c0314-866a-4a9b-bd59-89a3bf215272.png)

**Comment by wardz** [comment]
idk the correct layer for retail atm but you can probably fix it with one of these:
```
/run ClassicCastbars:GetCastbarFrame("target"):SetFrameStrata("HIGH")

/run ClassicCastbars:GetCastbarFrame("target"):SetFrameLevel(999)
```
