### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Drockzoids** [wardz/ClassicCastbars#78]
### What happened?

Log off and log back in and the player castbar position resets everytime.

### Is there any errors?

```shell
No errors, just doesn't save the position between logouts.
```

### Game Version

Classic Era

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

None

**Comment by wardz** [comment]
Are you on latest version v.1.5.6? Unable to reproduce here with /reload or manual logout.
Does typing `/run ClassicCastbars:SkinPlayerCastbar()` once after login set the position correctly?

**Comment by Drockzoids** [comment]
I actually uninstalled Improved Blizzard UI and I think it fixed itself.  Sorry about that, should have tried that first.  It seems to be working now.  Thanks.
