### ISSUE TITLE
Gold border texture

### ISSUE THREAD

**Issue by LootmanJP** [wardz/ClassicCastbars#8]
It'd be nice to have a gold varient of the default texture to match the nameplates like in this screenshot
![WoWScrnShot_010519_212523 jpg c142478477f20c970ff15e75391d09f8](https://user-images.githubusercontent.com/53992629/62831918-412cb300-bc1e-11e9-80b9-47266c25e401.jpg)

Thank you!

**Comment by wardz** [comment]
I won't be changing the texture itself as it's too much of a hassle, but I added an option to the latest version for changing border colors (+ more) so you can set it whatever you want.
