### ISSUE TITLE
[Bug]: Permanently ruined the UI in Wow Classic

### ISSUE THREAD

**Issue by Jadugarrrr** [wardz/ClassicCastbars#81]
### What happened?

After I downloaded this add-on for Classic Era and Hardcore servers, I didn't really like the interface design of it so I deleted the it. But even then, the interface from the add-on still existed. I reinstalled and deleted the add-on multiple times but the cast bars still look like the ones from the add-on. even after 1.15+ update. Is there any way to permanently delete the add-on?

### Game Version

Classic Era

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by wardz** [comment]
Target castbars are now built into the game by default. You can disable it in wow's own interface options.  
If you mean the textures themselves, you probably have some custom texture pack installed from somewhere else. These are installed in your Interface folder not Addons folder.
