### ISSUE TITLE
[Bug]: Classic Castbars needs to be updated for TWW 11.0.2

### ISSUE THREAD

**Issue by Drizzard2** [wardz/ClassicCastbars#84]
### What happened?

Currently Classic Castbars is causing major LUA issues with all manner of things on the latest patch of TWW. It needs to be updated.

### Game Version

Retail

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

Yes, issue still occurs.

**Comment by wardz** [comment]
Should be fixed now with v1.7.11.

**Comment by Drizzard2** [comment]
Thank you very much.
