### ISSUE TITLE
[Bug]: Spark bug on empowered spells (player cast bar)

### ISSUE THREAD

**Issue by mantumbi** [wardz/ClassicCastbars#85]
### What happened?

Hello,

Thanks for the great addon!

Playing as Evoker, when I use the player cast bar, the spark effect appears to eventually bug out on empowered spells. It is much taller and wider than usual. It seems to stay this way until relog/reload. 

Here is a picture example: [(https://imgur.com/a/TJml6YO)]

Thanks!

### Game Version

Retail

### Game Language

English

### Does the issue still occur when all other addons are temporarily disabled?

None

**Comment by mantumbi** [comment]
Seems to no longer be an issue with the latest update! Thanks a bunch! I'll let you know if it pops up again :)

**Comment by wardz** [comment]
Awesome. Closing ticket for now.
