### ISSUE TITLE
Cast bar doesn't react to cast interrupts

### ISSUE THREAD

**Issue by d3lavar** [wardz/ClassicCastbars#9]
**What is the problem? Is there any Lua errors?**
Cast bar doesn't react to cast interrupts. 

**What steps will reproduce the problem?**
Your target starts casting spell and then interrupts it, but castbar are still being displayed the cast.

**Does the issue still occur when all addons except ClassicCastbars are disabled?**
Yep

**Was it working in a previous version? If yes, which was the last good one?**
Nope

**Any additional info? If you play on a non english client, please include your locale:**
Im playing EN and RU locales

**Comment by wardz** [comment]
This is not a bug, but a Blizzard API limitation in classic. Nothing that can be done about it sadly.
